### PR TITLE
Attempting to fix missing BINSTAR_TOKEN issue

### PR DESCRIPTION
**Pull request by shadowwalkersb**
Not sure if it helps. Submitting just in case.

### CODE REVIEW

**Comment by jakirkham** [comment]
What is the reverting exactly?

**Comment by jakirkham** [comment]
NVM. Now it is clear. Didn't realize this was run before.

Yeah, try to get `conda-forge.yml` from commit ( https://github.com/conda-forge/freeglut-feedstock/commit/a5df3955265a576e908d60d5c85386e3216e9852 ) and then re-render.

**Comment by jakirkham** [comment]
Double checked and the string looks right to me.

**Comment by shadowwalkersb** [comment]
I checked out the commit you suggested. Did not produce any changes onto my revert.

**Comment by jakirkham** [comment]
Me too.

**Comment by jakirkham** [comment]
Figured there was no point in waiting for CI here as there is a massive backlog and this has no effect on anything, but deployment. Hoping that there will be some results once that clears.

**Comment by jakirkham** [comment]
Thanks for hunting this down. 😄

**Comment by shadowwalkersb** [comment]
Well, sorry for introducing it in the first place.

**Comment by jakirkham** [comment]
No worries.

**Pull request merged**
