### PR TITLE
Add regression test for CMake compilation and fix Windows

### PR DESCRIPTION
**Pull request by traversaro**
Disable compilation of static libraries on Windows to fix https://github.com/conda-forge/freeglut-feedstock/issues/26 .
Add CMake-based regression test to avoid regression such as  https://github.com/conda-forge/freeglut-feedstock/issues/26  in the future. 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
The PR is now ready for review (the PR description has been updated) @conda-forge/freeglut @wolfv @Tobias-Fischer .

**Comment by Tobias-Fischer** [comment]
Looks great to me, thanks! It would be great if this could be merged :)

**Comment by wolfv** [comment]
thanks! should we pull the previous build?

**Comment by traversaro** [comment]
> 
> 
> thanks! should we pull the previous build?

Good point, I don't know if the Windows one was usable in some form. I guess it can be done, but at the moment I do not have a clear picture of the benefit/risks involved in removing a build that has been in the server for ~1.5 months, even if it was broken.

**Pull request merged**
